/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./../../views/components/ApplicationLogo.vue')['default']
    BaseAnswerChoice: typeof import('./../../views/components/Auditor/Bases/BaseAnswerChoice.vue')['default']
    BaseButton: typeof import('./../../views/components/Animator/Bases/BaseButton.vue')['default']
    BaseButtonPopup: typeof import('./../../views/components/Auditor/Bases/Popup/BaseButtonPopup.vue')['default']
    BaseCard: typeof import('./../../views/components/Animator/Bases/BaseCard.vue')['default']
    BaseCheckbox: typeof import('./../../views/components/Animator/Bases/BaseCheckbox.vue')['default']
    BaseCountdown: typeof import('./../../views/components/Animator/Bases/BaseCountdown.vue')['default']
    BaseDurationRange: typeof import('./../../views/components/Animator/Bases/BaseDurationRange.vue')['default']
    BaseNotif: typeof import('./../../views/components/Auditor/Bases/BaseNotif.vue')['default']
    BaseRadioGroup: typeof import('./../../views/components/Animator/Bases/BaseRadioGroup.vue')['default']
    BasesTitrePopup: typeof import('./../../views/components/Auditor/Bases/Popup/BasesTitrePopup.vue')['default']
    BaseTab: typeof import('./../../views/components/Animator/Bases/BaseTab.vue')['default']
    BaseTabs: typeof import('./../../views/components/Animator/Bases/BaseTabs.vue')['default']
    BaseTimeInput: typeof import('./../../views/components/Animator/Bases/BaseTimeInput.vue')['default']
    ButtonDanger: typeof import('./../../views/components/Auditor/Bases/Button/ButtonDanger.vue')['default']
    ButtonPrimary: typeof import('./../../views/components/Auditor/Bases/Button/ButtonPrimary.vue')['default']
    ButtonProfile: typeof import('./../../views/components/Auditor/Bases/Button/ButtonProfile.vue')['default']
    ButtonSecondary: typeof import('./../../views/components/Auditor/Bases/Button/ButtonSecondary.vue')['default']
    Chat: typeof import('./../../views/components/Auditor/Home/Chat.vue')['default']
    ChatComponent: typeof import('./../../views/components/ChatComponent.vue')['default']
    Checkbox: typeof import('./../../views/components/Checkbox.vue')['default']
    DangerButton: typeof import('./../../views/components/DangerButton.vue')['default']
    DescriptionLive: typeof import('./../../views/components/Auditor/Home/DescriptionLive.vue')['default']
    Dropdown: typeof import('./../../views/components/Dropdown.vue')['default']
    DropdownLink: typeof import('./../../views/components/DropdownLink.vue')['default']
    Head: typeof import('@inertiajs/vue3')['Head']
    InputError: typeof import('./../../views/components/InputError.vue')['default']
    InputGroup: typeof import('./../../views/components/InputGroup.vue')['default']
    InputLabel: typeof import('./../../views/components/InputLabel.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    MessageItem: typeof import('./../../views/components/MessageItem.vue')['default']
    MiniaturePlayer: typeof import('./../../views/components/Auditor/MiniaturePlayer.vue')['default']
    Modal: typeof import('./../../views/components/Modal.vue')['default']
    MultipleInputGroup: typeof import('./../../views/components/Animator/Bases/MultipleInputGroup.vue')['default']
    NavLink: typeof import('./../../views/components/NavLink.vue')['default']
    Notifications: typeof import('./../../views/components/Auditor/Home/Notifications.vue')['default']
    Player: typeof import('./../../views/components/Auditor/Player.vue')['default']
    Popups: typeof import('./../../views/components/Auditor/Home/Popups.vue')['default']
    PopupSurveyMcq: typeof import('./../../views/components/Auditor/Home/Popup/PopupSurveyMcq.vue')['default']
    PopupText: typeof import('./../../views/components/Auditor/Home/Popup/PopupText.vue')['default']
    PrimaryButton: typeof import('./../../views/components/PrimaryButton.vue')['default']
    ProfileButton: typeof import('./../../views/components/Auditor/Bases/Button/ProfileButton.vue')['default']
    Recommandation: typeof import('./../../views/components/Auditor/Home/Recommandation.vue')['default']
    ResponsiveNavLink: typeof import('./../../views/components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./../../views/components/SecondaryButton.vue')['default']
    TextInput: typeof import('./../../views/components/TextInput.vue')['default']
    TextInputCity: typeof import('./../../views/components/Auditor/Bases/TextInput/TextInputCity.vue')['default']
    TextInputPostalCode: typeof import('./../../views/components/Auditor/Bases/TextInput/TextInputPostalCode.vue')['default']
  }
}
